[package]
name = "component-init-macro"
license.workspace = true
edition.workspace = true
version = "0.2.0"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full"] }
quote.workspace = true
